name: habs
description: This application provides a platform for patients to book appointments in Kitale District Hospital.
  Threfore, the application encompasses of two user interfaces, that of the patients and that of the doctor.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  font_awesome_flutter: ^8.8.1

  email_launcher: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
